print("True and False:", True and False)
print("True and True:", True and True)
print("False and False:", False and False)

print("True or False:", True or False)
print("True or True:", True or True)
print("False or False:", False or False)

print("True and 0:", True and 0)
print("1 and False:", 1 and False)
print("1 and 2:", 1 and 2)
print("2 and 1:", 2 and 1)
print("hello and 2:", "hello" and 2)
print("\"\" and 2:", "" and 2)
print("Hello and World:", "Hello" and "World")

print("Hello or World:", "Hello" or "World")
print("0 or True:", 0 or True)
print("1 or \"\":", 1 or "")
print("0 or None:", 0 or None)
print("None or 0:", None or 0)
